### ISSUE TITLE
SSL cert error & parsing relevant data : Solution

### ISSUE THREAD

**Issue by decyphertek-io** [nateuribe/Wazuh-IRIS-integration#2]
SSL Error Quick Fix:
-----------------------------
    
    git clone https://github.com/chadhardcastle/Wazuh-IRIS-integration.git
    cd Wazuh-IRIS-integration/
    vim custom-iris.py
    * Modify the last line of the python script: Send request to IRIS with SSL verification disabled
    * response = requests.post(hook_url, data=payload, headers={"Authorization": "Bearer " + api_key, "content-type": "application/json"}, verify=False)
    sudo cp custom-iris.py /var/ossec/integrations/custom-iris.py
    sudo chmod 750 /var/ossec/integrations/custom-iris.py
    sudo chown root:wazuh /var/ossec/integrations/custom-iris.py
    # AWS Wazuh on Amazon Linux requires these fixes. 
    sudo -H pip3 install requests
    # This is openssl missmatch, may not be needed 
    # sudo yum remove google-chrome && sudo yum update
    sudo -H pip3 install 'urllib3<2.0'
    
    sudo vim /var/ossec/etc/ossec.conf
    # page down place under local and above osec closing bracket
    <integration>
        <name>custom-iris.py</name>
        <hook_url>https://IP-OF-IRIS-SERVER/alerts/add</hook_url>
        <level>5</level>
        <api_key>API-KEY-HERE</api_key>
        <alert_format>json</alert_format>
    </integration>
    
    sudo systemctl restart wazuh-manager
    sudo cat /var/ossec/logs/ossec.log | grep "custom-iris.py"
    # UTC time is set to see the log time translated
    timedatectl

Data Parsing Issue - Updated Python script:
----------------------------------------------------------

    #!/usr/bin/env python3
    # custom-iris.py
    # Custom Wazuh integration script to send alerts to DFIR-IRIS
    
    import sys
    import json
    import requests
    
    # Function to create a formatted string from alert details
    def format_alert_details(alert_json):
        rule = alert_json.get("rule", {})
        agent = alert_json.get("agent", {})
        
        # Extracting MITRE information from the nested 'rule' structure
        mitre = rule.get("mitre", {})
        mitre_ids = ', '.join(mitre.get("id", ["N/A"]))
        mitre_tactics = ', '.join(mitre.get("tactic", ["N/A"]))
        mitre_techniques = ', '.join(mitre.get("technique", ["N/A"]))
    
        details = [
            f"Rule ID: {rule.get('id', 'N/A')}",
            f"Rule Level: {rule.get('level', 'N/A')}",
            f"Rule Description: {rule.get('description', 'N/A')}",
            f"Agent ID: {agent.get('id', 'N/A')}",
            f"Agent Name: {agent.get('name', 'N/A')}",
            f"MITRE IDs: {mitre_ids}",
            f"MITRE Tactics: {mitre_tactics}",
            f"MITRE Techniques: {mitre_techniques}",
            f"Location: {alert_json.get('location', 'N/A')}",
            f"Full Log: {alert_json.get('full_log', 'N/A')}"
        ]
        return '\n'.join(details)
    
    # Read parameters when integration is run
    alert_file = sys.argv[1]
    api_key = sys.argv[2]
    hook_url = sys.argv[3]
    
    # Read the alert file
    with open(alert_file) as f:
        alert_json = json.load(f)
    
    # Prepare alert details
    alert_details = format_alert_details(alert_json)
    
    # Generate request payload
    payload = json.dumps({
        "alert_title": alert_json.get("rule", {}).get("description", "No Description"),
        "alert_description": alert_details,
        "alert_source": "Wazuh",
        "alert_source_ref": alert_json.get("id", "Unknown ID"),
        "alert_source_link": "https://IP-OR-DOMAIN-WAZUH-SERVER/app/wazuh",  # Replace with actual Wazuh URL
        "alert_severity_id": alert_json.get("rule", {}).get("level", 1),
        "alert_status_id": 2,  # 'New' status
        "alert_source_event_time": alert_json.get("timestamp", "Unknown Timestamp"),
        "alert_note": "",
        "alert_tags": f"wazuh,{alert_json.get('agent', {}).get('name', 'N/A')}",
        "alert_customer_id": 1,  # '1' for default 'IrisInitialClient'
        "alert_source_content": alert_json  # raw log
    })
    
    # Send request to IRIS with SSL verification disabled
    response = requests.post(hook_url, data=payload, headers={"Authorization": "Bearer " + api_key, "content-type": "application/json"}, verify=False)
    
    sys.exit(0)

**Comment by nateuribe** [comment]
## SSL Error Quick Fix
See my previous [comment](https://github.com/nateuribe/Wazuh-IRIS-integration/issues/1#issuecomment-1815004451).

## Data Parsing Issue - Updated Python script
Neat, I've gone ahead and made the following changes in https://github.com/nateuribe/Wazuh-IRIS-integration/commit/6615ecba86f19bb1c804e522300ed107bacd4298.

**Comment by nateuribe** [comment]
These were resolved in https://github.com/nateuribe/Wazuh-IRIS-integration/commit/1d35fb6f84ce7318b82a83a09da32d79020c8ca2 and https://github.com/nateuribe/Wazuh-IRIS-integration/commit/6615ecba86f19bb1c804e522300ed107bacd4298 respectively. Thank you.
